// pages/_app.js
import '../src/app/globals.css'; // Import your global CSS
import Head from 'next/head';
import Layout from '../src/app/layout'; // Import your layout component
import 'bootstrap-icons/font/bootstrap-icons.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Pratik Shrestha</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
